version: '3.8'
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: tutor
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: tutor_db
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  chromadb:
    image: ghcr.io/chroma-core/chroma:latest
    ports:
      - '8000:8000'

volumes:
  pgdata:
